// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGQSlLsMMbYAURpW2dmbG8k9CJbrQpnj8',
    appId: '1:658280719618:web:7598ddeca45a3ab6630e1b',
    messagingSenderId: '658280719618',
    projectId: 'moj-notes-demo',
    authDomain: 'moj-notes-demo.firebaseapp.com',
    storageBucket: 'moj-notes-demo.appspot.com',
    measurementId: 'G-0HDWX4JKHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_IqyUM9Qr810PfNoasqjNIyDBeN68elk',
    appId: '1:658280719618:android:2ccb088e3fe18044630e1b',
    messagingSenderId: '658280719618',
    projectId: 'moj-notes-demo',
    storageBucket: 'moj-notes-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLv9E-2_WDiVgyLDAa2jNy2J9LWdo4k0I',
    appId: '1:658280719618:ios:27dd0e0b1284ae09630e1b',
    messagingSenderId: '658280719618',
    projectId: 'moj-notes-demo',
    storageBucket: 'moj-notes-demo.appspot.com',
    iosClientId: '658280719618-snb46agk34a7acpb5tsc2ep91fvijdb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLv9E-2_WDiVgyLDAa2jNy2J9LWdo4k0I',
    appId: '1:658280719618:ios:27dd0e0b1284ae09630e1b',
    messagingSenderId: '658280719618',
    projectId: 'moj-notes-demo',
    storageBucket: 'moj-notes-demo.appspot.com',
    iosClientId: '658280719618-snb46agk34a7acpb5tsc2ep91fvijdb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotesapp',
  );
}
